10.7
jellyfin/jellyfin-plugin-ldapauth pull request #60
Opened 2020-11-18 15:22 UTC by crobibero

2020-11-20 14:24 UTC, oddstr13 requested changes

2020-11-20 14:24 UTC, oddstr13 commented on LDAP-Auth/LDAP-Auth.csproj
> +    <TargetFramework>net5.0</TargetFramework>
build.yaml is the important file for CI, please include the changes to that file from #59 

```yaml
version: "10.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
```

2020-11-20 17:45 UTC, oddstr13 approved these changes

2020-11-22 02:36 UTC, joshuaboniface approved these changes

2020-11-22 02:37 UTC, merged

2020-11-22 02:37 UTC, joshuaboniface commented on LDAP-Auth/LDAP-Auth.csproj
>      <AssemblyVersion>9.0.0.0</AssemblyVersion>
Oof merged then realized this didn't get updated...